# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: main

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Add configuration files
      run: | 
        echo $CONFIG_JSON >> config.json
        echo '["abc"]' >> res/avatars.json
        echo '[{ "type": 0, "content": "", "actor": "" }]' >> res/beemovie.json
        wget 'https://raw.githubusercontent.com/jcquinlan/dnd-spells/master/spells.json' -O res/spells.json        
      env:
        CONFIG_JSON: ${{secrets.config_json}}
    
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: yarn
        
    - name: Install build dependencies
      run: sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
      
    - name: Install packages
      run: yarn install
    
    - name: Run checks
      run: yarn run check
