# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: main

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Add configuration files
      run: | 
        echo "declare const config: import('@core/Configuration').Configuration;
        export = config;" >> config.json.d.ts
        echo '["abc"]' >> res/avatars.json
    
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: yarn
        
    - name: Install build dependencies
      run: sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev graphicsmagick
      
    - name: Install packages
      run: yarn install
    
    - name: Build
      run: yarn build

    - name: Lint
      run: yarn lint

    - name: Test
      id: test
      run: yarn coverage

    - name: Test
      if: always()
      run: echo ${{ steps.test.outcome }} ${{ hashFiles('coverage/index.html') }}

    - name: Upload coverage
      if: always() && steps.test.outcome != 'skipped'
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage/
